config/routes.rb
Rails.application.routes.draw do
  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  resources :items

  resources :products do
    resources :variants
  end

  resources :orders do
    resources :fulfillments
    resources :line_items
  end

  resources :customers do
    resources :addresses
  end

  root :to => 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :addresses, :primary_key => :shopify_id, :dependent => :destroy

  def self.import
    @shopify_customers = ShopifyAPI::Customer.find(:all)
    @shopify_customers.each do |shopify_customer|
      next if Customer.find_by_shopify_id(shopify_customer.id)
      customer = Customer.new
      customer.accepts_marketing = shopify_customer.accepts_marketing
      customer.shopify_created_at = shopify_customer.created_at
      customer.default_address_address1 = shopify_customer.default_address.address1
      customer.default_address_address2 = shopify_customer.default_address.address2
      customer.default_address_city = shopify_customer.default_address.city
      customer.default_address_company = shopify_customer.default_address.company
      customer.default_address_country = shopify_customer.default_address.country
      customer.default_address_first_name = shopify_customer.default_address.first_name
      customer.default_address_id = shopify_customer.default_address.id
      customer.default_address_last_name = shopify_customer.default_address.last_name
      customer.default_address_phone = shopify_customer.default_address.phone
      customer.default_address_province = shopify_customer.default_address.province
      customer.default_address_zip = shopify_customer.default_address.zip
      customer.default_address_province_code = shopify_customer.default_address.province_code
      customer.default_address_country_code = shopify_customer.default_address.country_code
      customer.default_address_default = shopify_customer.default_address.default
      customer.email = shopify_customer.email
      customer.first_name = shopify_customer.first_name
      customer.shopify_id = shopify_customer.id
      customer.last_name = shopify_customer.last_name
      customer.last_order_id = shopify_customer.last_order_id
      customer.last_order_name = shopify_customer.last_order_name
      customer.note = shopify_customer.note
      customer.orders_count = shopify_customer.orders_count
      customer.state = shopify_customer.state
      customer.tags = shopify_customer.tags
      customer.total_spent = shopify_customer.total_spent
      customer.updated_at = shopify_customer.updated_at
      customer.verified_email = shopify_customer.verified_email
      customer.save
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  around_filter :shopify_session, :except => 'welcome'

  def welcome
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login"
  end

  def index
    @customers = Customer.all
    @shopify_customers = ShopifyAPI::Customer.find(:all)
  end

  def show
    @customer = Customer.find(params[:id])
    @addresses = Address.all
  end

  def new
    Customer.import
    Address.import
    redirect_to customers_path
  end

  def create
    @customer = Customer.new(customer_params)

    @customer.save
    redirect_to @customer
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to customers_path
  end

  private
    def customer_params
      params.require(:customer).permit!
    end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<p style="font-size: 20px"><%= link_to 'Import Shopify Customers', new_customer_path %></p>

<br><br><br>

<h1>All Customers</h1>
<table border="1" style="width:100%">
  <tr>
    <th>shopify_id</th>
    <th>first_name</th>
    <th>last_name</th>
    <th>email</th>
    <th>default_address_address1</th>
    <th>default_address_city</th>
  <tr>

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.shopify_id %></td>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.default_address_address1 %></td>
      <td><%= customer.default_address_city %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Delete', customer_path(customer), method: :delete, data: { confirm:'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br><br><br>

<h1>Shopify Customers</h1>
<table border="1" style="width:100%">
  <tr>
    <th>id</th>
    <th>first_name</th>
    <th>last_name</th>
    <th>default_address_address1</th>
    <th>default_address_city</th>
    <th>default_address_province_code</th>
  </tr>
  <% @shopify_customers.each do |t| %>
    <tr>
      <td><%= t.id %></td>
      <td><%= t.first_name %></td>
      <td><%= t.last_name %></td>
      <td><%= t.default_address.address1 %></td>
      <td><%= t.default_address.city %></td>
      <td><%= t.default_address.province_code %></td>
      <% t.addresses.each do |f| %>
        <tr>
          <td><%= f.id %></td>
          <td><%= f.address1 %></td>
          <td><%= f.city %></td>
          <td><%= f.province_code %></td>
        </tr>
      <% end %>
    </tr>
  <% end %>
</table>
<br><br>
<h3><%= link_to 'Back Home', controller: 'home' %></h3>

app/views/customers/new.html.erb
<%= form_for :customer, url: customers_path  do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/customers/show.html.erb
<h1>Customer Information</h1>
<p>
  <strong>accepts_marketing:</strong>
  <%= @customer.accepts_marketing %>
</p>
<p>
  <strong>shopify_created_at:</strong>
  <%= @customer.shopify_created_at %>
</p>
<p>
  <strong>default_address_address1:</strong>
  <%= @customer.default_address_address1 %>
</p>
<p>
  <strong>default_address_address2:</strong>
  <%= @customer.default_address_address2 %>
</p>
<p>
  <strong>default_address_city:</strong>
  <%= @customer.default_address_city %>
</p>
<p>
  <strong>default_address_company:</strong>
  <%= @customer.default_address_company %>
</p>
<p>
  <strong>default_address_country:</strong>
  <%= @customer.default_address_country %>
</p>
<p>
  <strong>default_address_first_name:</strong>
  <%= @customer.default_address_first_name %>
</p>
<p>
  <strong>default_address_id:</strong>
  <%= @customer.default_address_id %>
</p>
<p>
  <strong>default_address_last_name:</strong>
  <%= @customer.default_address_last_name %>
</p>
<p>
  <strong>default_address_phone:</strong>
  <%= @customer.default_address_phone %>
</p>
<p>
  <strong>default_address_province:</strong>
  <%= @customer.default_address_province %>
</p>
<p>
  <strong>default_address_zip:</strong>
  <%= @customer.default_address_zip %>
</p>
<p>
  <strong>default_address_province_code:</strong>
  <%= @customer.default_address_province_code %>
</p>
<p>
  <strong>default_address_country_code:</strong>
  <%= @customer.default_address_country_code %>
</p>
<p>
  <strong>default_address_default:</strong>
  <%= @customer.default_address_default %>
</p>
<p>
  <strong>email:</strong>
  <%= @customer.email %>
</p>
<p>
  <strong>first_name:</strong>
  <%= @customer.first_name %>
</p>
<p>
  <strong>email:</strong>
  <%= @customer.email %>
</p>
<p>
  <strong>shopify_id:</strong>
  <%= @customer.shopify_id %>
</p>
<p>
  <strong>last_name:</strong>
  <%= @customer.last_name %>
</p>
<p>
  <strong>last_order_id:</strong>
  <%= @customer.last_order_id %>
</p>
<p>
  <strong>last_order_name:</strong>
  <%= @customer.last_order_name %>
</p>
<p>
  <strong>note:</strong>
  <%= @customer.note %>
</p>
<p>
  <strong>orders_count:</strong>
  <%= @customer.orders_count %>
</p>
<p>
  <strong>state:</strong>
  <%= @customer.state %>
</p>
<p>
  <strong>tags:</strong>
  <%= @customer.tags %>
</p>
<p>
  <strong>total_spent:</strong>
  <%= @customer.total_spent %>
</p>
<p>
  <strong>updated_at:</strong>
  <%= @customer.updated_at %>
</p>
<p>
  <strong>verified_email:</strong>
  <%= @customer.verified_email %>
</p>

<br><br>

<h1>Addresses</h1>
<%= render @customer.addresses %>
<br><br>

<p>
  <%= link_to 'Back to Customers', customers_path%>
</p>