config/routes.rb
Rails.application.routes.draw do
  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  resources :items

  resources :products do
    resources :variants
  end

  resources :orders do
    resources :fulfillments
    resources :line_items
  end

  resources :customers do
    resources :addresses
  end

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  def self.import
    @products = ShopifyAPI::Product.find(:all, :params => {:limit => 10})
    @products.each do |product|
      #next if Item.find_by_shopify_id(product.id)
      item = Item.new
      #item.shopify_id = product.id
      item.title = product.title
      item.price_range = product.price_range
      item.save
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  around_filter :shopify_session, :except => 'welcome'

  def welcome
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login"
  end



  def index
    @items = Item.all

    @products = ShopifyAPI::Product.find(:all, :params => {:limit => 10})
  end

  def show
    @item = Item.find(params[:id])

    Item.import
    
  end

  def new
  end

  def create
    @item = Item.new(item_params)

    @item.save
    redirect_to @item
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:title, :price_range)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1>All Items</h1>
<table border="1" style="width:100%">
  <tr>
    <th>Title</th>
    <th>Price Range</th>
  <tr>

  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.price_range %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm:'Are you sure?'} %></td>
    </tr>
  <% end %>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.price_range %></td>
      <td><%= product.id %></td>
    </tr>
  <% end %>

</table>
<br><br>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= form_for :item, url: items_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price_range %><br>
    <%= f.text_field :price_range %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/show.html.erb
<h1>Item Information</h1>
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>
<p>
  <strong>Price Range:</strong>
  <%= @item.price_range %>
</p>