config/routes.rb
Rails.application.routes.draw do
  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  resources :items

  resources :products do
    resources :variants
  end

  resources :orders do
    resources :fulfillments
    resources :line_items
  end

  resources :customers do
    resources :addresses
  end

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :variants, :primary_key => :shopify_id, :dependent => :destroy

  def self.import
    @shopify_products = ShopifyAPI::Product.find(:all)
    @shopify_products.each do |shopify_product|
      next if Product.find_by_shopify_id(shopify_product.id)
      product = Product.new
      product.shopify_id = shopify_product.id
      product.title = shopify_product.title
      product.body_html = shopify_product.body_html
      product.shopify_created_at = shopify_product.created_at
      product.handle = shopify_product.handle
      product.images = shopify_product.images
      product.options = shopify_product.options
      product.product_type = shopify_product.product_type
      product.published_at = shopify_product.published_at
      product.published_scope = shopify_product.published_scope
      product.tags = shopify_product.tags
      product.shopify_updated_at = shopify_product.updated_at
      product.vendor = shopify_product.vendor
      product.save
    end

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  around_filter :shopify_session, :except => 'welcome'

  def welcome
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login"
  end

  def index
    @products = Product.all
    @shopify_products = ShopifyAPI::Product.find(:all)

    @variants = Variant.all
    @shopify_variants = ShopifyAPI::Variant.find(:all)
  end

  def show
    @product = Product.find(params[:id])
    @variants = Variant.all
  end

  def new
    Product.import
    Variant.import
    redirect_to products_path
  end

  def create
    @product = Product.new(product_params)

    @product.save
    redirect_to @product
  end

  def update
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit!
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Products Import</h1>
<p>Your shopify products are being imported, you are being redirected</p>

app/views/products/index.html.erb
<p style="font-size: 20px"><%= link_to 'Import Shopify Products', new_product_path %></p>
<br><br><br>
<h1>Products</h1>
<table border="1" style="width:100%">
  <tr>
    <th>shopify_id</th>
    <th>title</th>
    <th>vendor</th>
    <th>handle</th>
    <th>shopify_created_at</th>
  <tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.shopify_id %></td>
      <td><%= product.title %></td>
      <td><%= product.vendor %></td>
      <td><%= product.handle %></td>
      <td><%= product.shopify_created_at %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm:'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br><br>

<h1>Shopify Products</h1>
<table border="1" style="width:100%">
  <tr>
    <th>id</th>
    <th>title</th>
    <th>vendor</th>
    <th>handle</th>
    <th>created_at</th>
  </tr>

  <% @shopify_products.each do |t| %>
    <tr>
      <td><%= t.id %></td>
      <td><%= t.title %></td>
      <td><%= t.vendor %></td>
      <td><%= t.handle %></td>
      <td><%= t.created_at %></td>
    </tr>

    <% t.variants.each do |product_variant| %>
      <tr>
        <td>id: <%= product_variant.id %></td>
        <td>product_id: <%= product_variant.product_id %></td>
        <td>price: <%= product_variant.price %></td>
        <td>title: <%= product_variant.title %></td>
      </tr>
    <% end %>

  <% end %>

</table>
<h3><%= link_to 'Back Home', controller: 'home' %></h3>

app/views/products/new.html.erb
<h1>Import Product</h1>
<p>Your products are being imported, you will be redirected back</p>

app/views/products/show.html.erb
<h1>Product Information</h1>
<p>
  <strong>shopify_id:</strong>
  <%= @product.shopify_id %>
</p>
<p>
  <strong>title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>id:</strong>
  <%= @product.id %>
</p>
<p>
  <strong>body_html:</strong>
  <%= @product.body_html %>
</p>
<p>
  <strong>shopify_created_at:</strong>
  <%= @product.shopify_created_at %>
</p>
<p>
  <strong>created_at</strong>
  <%= @product.created_at %>
<p>
  <strong>handle:</strong>
  <%= @product.handle %>
</p>
<p>
  <strong>images:</strong>
  <%= @product.images %>
</p>
<p>
  <strong>options:</strong>
  <%= @product.options %>
</p>
<p>
  <strong>product_type:</strong>
  <%= @product.product_type %>
</p>
<p>
  <strong>published_at:</strong>
  <%= @product.published_at %>
</p>
<p>
  <strong>published_scope:</strong>
  <%= @product.published_scope %>
</p>
<p>
  <strong>tags:</strong>
  <%= @product.tags %>
</p>
<p>
  <strong>updated_at:</strong>
  <%= @product.shopify_updated_at %>
</p>
<p>
  <strong>vendor:</strong>
  <%= @product.vendor %>
</p>
<br><br>

<h1>Variants</h1>
<%= render @product.variants %>
<br><br>
<p>
  <%= link_to 'Back to Products', products_path%>
</p>